### ISSUE TITLE
Cannot read properties of undefined (reading 'sendRequest')

### ISSUE THREAD

**Issue by brendahon** [joyceerhl/vscode-mssql-chat#2]
@joyceerhl 

Hi Joyce,

I tried to use code insider and set up this chat extension. But I received captioned error. Attached please find the screen capture below for your reference of the error I got. Would  you please advise any steps I missed for the setup? 

"Cannot read properties of undefined (reading 'sendRequest')" 

![issue](https://github.com/joyceerhl/vscode-mssql-chat/assets/30277820/993c9550-e40e-4094-8614-5ec76b5c57db)

![issue2](https://github.com/joyceerhl/vscode-mssql-chat/assets/30277820/14bc240a-8349-49c4-8741-8c631375be07)

Regards,
Brenda

**Comment by joyceerhl** [comment]
That indicates that there were no available language models to handle the chat request. Are you on the latest Copilot Chat (v0.17.2024061702) and VS Code Insiders (1.91-insider)?

**Comment by brendahon** [comment]
I tried to use codespace to make sure GitHub Copilot Chat (v0.17.2024061702) is installed. 
![image](https://github.com/joyceerhl/vscode-mssql-chat/assets/30277820/8d3d85aa-a29d-4bb8-b44a-d419b087bea8)

However, same error "Cannot read properties of undefined (reading 'sendRequest')" is encountered. 
![image](https://github.com/joyceerhl/vscode-mssql-chat/assets/30277820/4e27059c-5ea7-4e26-9b37-193da7082795)


Would you please clarify the Setup step 1&2 below you mentioned in README.md? Does it mean download your code and load it in my codespace? And how exactly the steps are to "install this extension & install the fork of MS SQL extension"?

1. Install this extension
2. Install this fork of the MS SQL extension https://github.com/joyceerhl/vscode-mssql

**Comment by joyceerhl** [comment]
> "Cannot read properties of undefined (reading 'sendRequest')"

This was a bug in the Copilot Chat extension and should now be fixed, please make sure you're on VS Code Insiders and the latest prerelease.

> And how exactly the steps are to "install this extension & install the fork of MS SQL extension"?

You'll need to create a local build of both extensions by doing `npm i; npm run compile; npx vsce package` for both and installing the produced `.vsix` extension files in your codespace.

**Comment by brendahon** [comment]
I am not able to build your vscode-mssql successfully with the screen capture of the command & error below. May I ask for your advice how to fix it?
![image](https://github.com/joyceerhl/vscode-mssql-chat/assets/30277820/ab359832-c65d-4a01-975f-502e1065e7ed)
