### ISSUE TITLE
Can't get Database Context

### ISSUE THREAD

**Issue by aplaxas** [joyceerhl/vscode-mssql-chat#4]
The following function in utils.ts is not working,
export async function getDatabaseContext(includeHeader = true) {
	const sqlExtensionApi = await vscode.extensions.getExtension('ms-mssql.mssql')?.activate();
	script ??= await sqlExtensionApi.getDatabaseCreateScript?.();
	if (!includeHeader && script) { return script; }
	return `Here are the creation scripts that were used to create the tables in my database. Pay close attention to the tables and columns that are available in my database:
${script}`;
}

Root Cause: 
  mssql extension doesn't export "getDatabaseCreateScript" method.

mssql:  v1.26.0
https://github.com/microsoft/vscode-mssql

**Comment by joyceerhl** [comment]
Please see https://github.com/joyceerhl/vscode-mssql-chat?tab=readme-ov-file#setup

**Comment by aplaxas** [comment]
I have a desktop environment and installed ms-sql via vsix. 
Does the package only work on the codebase?
